version: "3"
services: 
  play:
    image: jorgemartinezpizarro/bitcoinprivacy:SNAPSHOT
    volumes:
      - "$PWD/play/play.conf:/conf/play.conf"
      - "$PWD/play/logback.xml:/conf/logback.xml"
    ports:
      - 9000:9000
    networks:
      bge_network:
        ipv4_address: 172.18.0.6
    depends_on:
      - bge
      - bgeapi
      - bitcoin
      - postgres
  bge:
    image: jorgemartinezpizarro/bge:3.3-SNAPSHOT
    environment:
      JAVA_MAX_MEM: 20g
      JAVA_MIN_MEM: 8g
    depends_on:
      - postgres
      - bitcoin
    networks:
      bge_network:
        ipv4_address: 172.18.0.4 
    volumes:
      - "$PWD/bge/bge.conf:/conf/bge.conf"
      - "$PWD/bge/logback.xml:/conf/logback.xml"
      - "$DATA_FOLDER/bitcoin:/root/.bitcoin"
      - "$DATA_FOLDER/blockchain:/root/Bitcoin-Graph-Explorer/blockchain"
  bgeapi: 
    image: jorgemartinezpizarro/bgeapi:SNAPSHOT
    networks: 
      bge_network:
        ipv4_address: 172.18.0.5 
    ports:
      - 8080:8080
    volumes:
      - "$PWD/bgeapi/bgeapi.conf:/conf/bgeapi.conf"
      - "$PWD/bgeapi/logback.xml:/conf/logback.xml"
  bitcoin:
    image: ruimarinho/bitcoin-core:0.16.0
    networks: 
      bge_network:
        ipv4_address: 172.18.0.2 
    ports:
      - 8333:8333
    command: 
      -printtoconsole
      -conf=/etc/bitcoin/bitcoin.conf
    volumes:
      - "$DATA_FOLDER/bitcoin:/home/bitcoin/.bitcoin"
      - "$PWD/bitcoin/bitcoin.conf:/etc/bitcoin/bitcoin.conf"
  postgres:
    image: postgres:10.1
    networks:
      bge_network:
        ipv4_address: 172.18.0.3
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: trivial
      POSTGRES_DB: postgres
    volumes:
      - "$DATA_FOLDER/psql:/var/lib/postgresql/data"
      - "$PWD/postgres/postgres.conf:/etc/postgresql/postgresql.conf"
    command:
      -c
      config_file=/etc/postgresql/postgresql.conf
networks:
  bge_network:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.18.0.0/24
