version: "2.1"
services: 
  play:
    image: jorgemartinezpizarro/bitcoinprivacy:SNAPSHOT
    volumes:
      - "$PWD/play/play.conf:/conf/play.conf"
      - "$PWD/play/logback.xml:/conf/logback.xml"
    ports:
      - 9000:9000
    networks:
      bge_network:
        ipv4_address: 172.18.0.6
    depends_on:
      bge:
        condition: service_started
      bgeapi:
        condition: service_started
      bitcoin:
        condition: service_started
      postgres:
        condition: service_started
    environment: 
      JAVA_MAX_MEM: 1G
    command: "java -Dconfig.file=/conf/play.conf -Dlogback.configurationFile=/conf/logback.xml -jar /root/play-bitcoinprivacy/bitcoinprivacy.jar"
  bge:
    image: jorgemartinezpizarro/bge:SNAPSHOT
    depends_on:
      postgres:
        condition: service_started
      bitcoin:
        condition: service_started
    networks:
      bge_network:
        ipv4_address: 172.18.0.4 
    volumes:
      - "$PWD/bge/bge.conf:/conf/bge.conf"
      - "$PWD/bge/logback.xml:/conf/logback.xml"
      - "$DATA_FOLDER/bitcoin:/root/.bitcoin"
      - "$DATA_FOLDER/blockchain:/root/Bitcoin-Graph-Explorer/blockchain"
    command: "java -Dconfig.file=/conf/bge.conf -Dlogback.configurationFile=/conf/logback.xml -jar /root/bge/bge.jar start"
  bgeapi: 
    image: jorgemartinezpizarro/bgeapi:SNAPSHOT
    networks: 
      bge_network:
        ipv4_address: 172.18.0.5 
    environment: 
      JAVA_MAX_MEM: 1G
    volumes:
      - "$PWD/bgeapi/bgeapi.conf:/conf/bgeapi.conf"
      - "$PWD/bgeapi/logback.xml:/conf/logback.xml"
    ports: 
      - 8080:8080
    command: "java -Dconfig.file=/conf/bgeapi.conf -Dlogback.configurationFile=/conf/logback.xml -jar /root/bge/bgeapi.jar"
  bitcoin:
    image: ruimarinho/bitcoin-core:0.15.1
    networks: 
      bge_network:
        ipv4_address: 172.18.0.2 
    command: 
      -printtoconsole
      -testnet=1
    volumes:
      - "$DATA_FOLDER/bitcoin:/home/bitcoin/.bitcoin"
  postgres:
    image: postgres:10.1
    networks: 
      bge_network:
        ipv4_address: 172.18.0.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: trivial
      POSTGRES_DB: postgres
    volumes:
      - "$DATA_FOLDER/psql:/var/lib/postgresql/data"
networks:
  bge_network:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.18.0.0/24
