version: "2.1"
services: 
  play:
    image: jorgemartinezpizarro/bitcoinprivacy:SNAPSHOT
    build: ./play
    volumes:
      - "$PWD/play/custom.conf:/conf/custom.conf"
    ports:
      - 9000:9000
    networks:
      bge_network:
        ipv4_address: 172.18.0.6
    depends_on:
      bge:
        condition: service_started
      bgeapi:
        condition: service_started
      bitcoin:
        condition: service_started
      postgres:
        condition: service_started
    command: "java -Dconfig.file=/conf/custom.conf -jar /root/play-bitcoinprivacy/bitcoinprivacy.jar"
    environment: 
      JAVA_MAX_MEM: 1G
    healthcheck:
      test: ["CMD", "testURI", "http://localhost:9000/faq"]
      interval: 15s
      timeout: 20s
      retries: 40

  bge:
    image: jorgemartinezpizarro/bge:SNAPSHOT
    build: ./bge
    depends_on:
      postgres:
        condition: service_started
      bitcoin:
        condition: service_started
    networks:
      bge_network:
        ipv4_address: 172.18.0.4 
    volumes:
      - "$PWD/bge/bge.conf:/conf/bge.conf"
      - "$DATA_FOLDER/bitcoin:/root/.bitcoin"
      - "$DATA_FOLDER/blockchain:/root/Bitcoin-Graph-Explorer/blockchain"
    command: "java -Dconfig.file=/conf/bge.conf -jar /root/bge/bge.jar start --force"

  bgeapi: 
    image: jorgemartinezpizarro/bgeapi:SNAPSHOT
    build: ./bgeapi
    networks: 
      bge_network:
        ipv4_address: 172.18.0.5 
    environment: 
      JAVA_MAX_MEM: 1G
    volumes:
      - "$PWD/bgeapi/custom.conf:/conf/custom.conf"
    ports: 
      - 8080:8080
    command: "java -Dconfig.file=/conf/custom.conf -jar /root/bge/bgeapi.jar"

  bitcoin:
    image: ruimarinho/bitcoin-core:0.15.1
    networks: 
      bge_network:
        ipv4_address: 172.18.0.2 
    command: 
      -printtoconsole
      -testnet=1
    volumes:
      - "$DATA_FOLDER/bitcoin:/home/bitcoin/.bitcoin"
 
  postgres:
    image: postgres:10.1
    networks: 
      bge_network:
        ipv4_address: 172.18.0.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: trivial
      POSTGRES_DB: postgres
    volumes:
      - "$DATA_FOLDER/psql:/var/lib/postgresql/data"

networks:
  bge_network:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.18.0.0/24
