vesion: 0.0.1

services:

dependent containers

until all containers are healthy

bge:
    image: hub.docker.com/postgres:10.1-alpine
    entrypoint: echo "Postgres started"
    depends_on:
      dataplatform:
        condition: service_healthy
      datamanager:
        condition: service_healthy
      dataintegration:
        condition: service_healthy
      stardog:
        condition: service_healthy
      apache2:
        condition: service_healthy

  apache2:
    image: docker-registry.eccenca.com/eccenca-apache2:v2.1.2
    volumes:
      - "${DESTINATON}/conf/apache2/default.conf:/etc/apache2/sites-enabled/000-default.conf"
      - "${DESTINATON}/conf/apache2/healthcheck.sh:/opt/healthcheck.sh"
    environment:
      - "DEPLOY_HOST=${DEPLOY_HOST}"
      - "DEPLOY_BASE_URL=${DEPLOY_BASE_URL}"
    ports:
      - "${PUBLIC_PORT}:80"
    healthcheck:
      test: ["CMD", "bash", "/opt/healthcheck.sh"]
      interval: 15s
      timeout: 20s
      retries: 40
    # aliasing docker.local for local deployment. This is not needed for our remote deployments
    extra_hosts:
      - "docker.local:127.0.0.1"


  
